services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mashgin_api
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://root:root@db:5432/mashgin_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mashgin_network
  db:
    image: postgres:17.4-alpine
    restart: always
    container_name: mashgin_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mashgin_db
    ports:
      - "5432:5432"
    networks:
      - mashgin_network
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
networks:
  mashgin_network:
    driver: bridge
