services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mashgin_api
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://admin:admin@db:5432/mashgin_db
    depends_on:
      - db
    networks:
      - mashgin_network
  db:
    image: postgres:17.4-alpine
    restart: always
    container_name: mashgin_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mashgin_db
    ports:
      - "5432:5432"
    networks:
      - mashgin_network
networks:
  mashgin_network:
    driver: bridge
